// <auto-generated />
using System;
using HttpClientTest.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HttpClientTest.Repository.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HttpClientTest.Entities.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@localhost",
                            Name = "Admin",
                            Password = "123456",
                            Surname = "Guest",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "member@localhost",
                            Name = "Member",
                            Password = "123456",
                            Surname = "Guest",
                            Username = "member"
                        },
                        new
                        {
                            Id = 3,
                            Email = ".@gmail.com",
                            Name = "Kezlik",
                            Password = "x_kMIA",
                            Surname = "Abacı",
                            Username = "Bulut.Akan50"
                        },
                        new
                        {
                            Id = 4,
                            Email = ".28@yahoo.com",
                            Name = "Altan",
                            Password = "6Fl7gv",
                            Surname = "Gürmen",
                            Username = "Boncuk48"
                        },
                        new
                        {
                            Id = 5,
                            Email = "_25@yahoo.com",
                            Name = "Adlıbeğ",
                            Password = "1FVSAd",
                            Surname = "Akyürek",
                            Username = "Gonul_Ozbir46"
                        },
                        new
                        {
                            Id = 6,
                            Email = ".@gmail.com",
                            Name = "Ekeç",
                            Password = "4VdxIH",
                            Surname = "Tütüncü",
                            Username = "Adraman.Kuzucu"
                        },
                        new
                        {
                            Id = 7,
                            Email = ".@hotmail.com",
                            Name = "Ilgın",
                            Password = "oMYTiy",
                            Surname = "Baykam",
                            Username = "Adiguzel20"
                        },
                        new
                        {
                            Id = 8,
                            Email = "96@yahoo.com",
                            Name = "Buzaçtutuk",
                            Password = "iSwmF8",
                            Surname = "Kaplangı",
                            Username = "Kivanc_Turkyilmaz"
                        },
                        new
                        {
                            Id = 9,
                            Email = "71@yahoo.com",
                            Name = "Çemgen",
                            Password = "LqnmGe",
                            Surname = "Evliyaoğlu",
                            Username = "Baltar_Sarioglu"
                        },
                        new
                        {
                            Id = 10,
                            Email = "70@hotmail.com",
                            Name = "Bozkurt",
                            Password = "c93AW1",
                            Surname = "Okumuş",
                            Username = "Bagtas_Duygulu93"
                        },
                        new
                        {
                            Id = 11,
                            Email = "_81@gmail.com",
                            Name = "Bağatursepi",
                            Password = "qGuggl",
                            Surname = "Babacan",
                            Username = "Kizilalma.Koc62"
                        },
                        new
                        {
                            Id = 12,
                            Email = "_49@yahoo.com",
                            Name = "Alpyörük",
                            Password = "gh8zpX",
                            Surname = "Çetiner",
                            Username = "Abaka72"
                        });
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.AppUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppRoleId")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppRoleId");

                    b.HasIndex("AppUserId", "AppRoleId");

                    b.ToTable("AppUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppRoleId = 1,
                            AppUserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppRoleId = 2,
                            AppUserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppRoleId = 2,
                            AppUserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppRoleId = 2,
                            AppUserId = 4
                        },
                        new
                        {
                            Id = 5,
                            AppRoleId = 2,
                            AppUserId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppRoleId = 2,
                            AppUserId = 6
                        },
                        new
                        {
                            Id = 7,
                            AppRoleId = 2,
                            AppUserId = 7
                        },
                        new
                        {
                            Id = 8,
                            AppRoleId = 2,
                            AppUserId = 8
                        },
                        new
                        {
                            Id = 9,
                            AppRoleId = 2,
                            AppUserId = 9
                        },
                        new
                        {
                            Id = 10,
                            AppRoleId = 2,
                            AppUserId = 10
                        },
                        new
                        {
                            Id = 11,
                            AppRoleId = 2,
                            AppUserId = 11
                        },
                        new
                        {
                            Id = 12,
                            AppRoleId = 2,
                            AppUserId = 12
                        });
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Blogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 10, 3, 12, 7, 50, 54, DateTimeKind.Local).AddTicks(5326),
                            Description = "Consectetur ab ut quasi ducimus numquam dicta quasi. Consequatur qui molestiae quia için. İçin çünkü beğendim dolorem çobanın quasi kutusu tempora blanditiis. Dolorem eum dağılımı modi.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Balıkhaneye cesurca adresini qui otobüs ışık ipsum ad değirmeni eaque ki nisi voluptas eve teldeki dergi yapacakmış çünkü dolorem magni quia.",
                            Title = "Sıla gitti quia ut un quis."
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 7, 4, 17, 18, 21, 391, DateTimeKind.Local).AddTicks(1403),
                            Description = "Labore ad mıknatıslı. Nesciunt voluptatem qui dolore gazete sit. Karşıdakine quis vitae praesentium öyle sandalye adanaya. Tv aut ipsum hesap sed tv. İusto ona ut ipsam.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Gidecekmiş accusantium sevindi sed açılmadan nostrum de neque umut in kapının yaptı magni.",
                            Title = "Mi lakin."
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 12, 6, 19, 14, 55, 291, DateTimeKind.Local).AddTicks(4826),
                            Description = "Mi eaque ipsam. Explicabo architecto voluptatem dolores corporis odio. Un un et. Corporis nesciunt kapının rem vitae totam kapının ex.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Nihil sıfat et consequuntur kalemi patlıcan ipsam koştum filmini sıla oldular ekşili dolorem nihil gazete illo totam ve aut quia.",
                            Title = "Voluptatem dolor dicta corporis sevindi dolayı ea doloremque hesap ullam ducimus."
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 12, 10, 9, 12, 3, 729, DateTimeKind.Local).AddTicks(3759),
                            Description = "İncidunt in ipsum quia sarmal qui gitti enim umut explicabo. Sandalye veritatis quae eius koştum ea amet ekşili gitti. Makinesi totam türemiş veniam tv ut iure nisi sit.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Aperiam numquam dağılımı aut çorba incidunt ratione quis için doloremque çarpan explicabo quasi koşuyorlar koşuyorlar bahar illo aut de doğru.",
                            Title = "Sıradanlıktan et in deleniti ut uzattı sandalye ekşili blanditiis."
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 8, 11, 16, 59, 13, 803, DateTimeKind.Local).AddTicks(4777),
                            Description = "Ut eius olduğu patlıcan ipsum molestiae labore öyle. Ratione değirmeni velit non dicta ışık kutusu çünkü. Quaerat quis ut perferendis. Beğendim kalemi laudantium beğendim tempora. De quasi ut gülüyorum architecto quia magni. Quaerat okuma bilgiyasayarı.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Gidecekmiş mi ut yaptı iure ut aperiam adipisci amet autem amet totam ab veniam rem ama sıfat blanditiis qui commodi koşuyorlar açılmadan doğru eaque sevindi dolorem için.",
                            Title = "Voluptatem neque sed çorba et."
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 7, 29, 0, 4, 6, 770, DateTimeKind.Local).AddTicks(1395),
                            Description = "Quaerat bundan makinesi eum. Ona ışık aliquam çobanın perferendis. Bilgisayarı quis voluptatem voluptatem beatae çorba sequi çarpan bilgiyasayarı odit. Dağılımı dolorem filmini gülüyorum incidunt koşuyorlar eius telefonu.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Layıkıyla labore quis ama numquam quia magni reprehenderit minima sequi anlamsız et teldeki.",
                            Title = "Teldeki totam gitti hesap iusto commodi okuma."
                        },
                        new
                        {
                            Id = 7,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2023, 5, 28, 13, 33, 56, 834, DateTimeKind.Local).AddTicks(188),
                            Description = "Voluptatem aut teldeki illo consequatur ipsam fugit. Voluptatem kalemi dolayı. Eum quia hesap anlamsız nisi sokaklarda sit et alias cesurca. Sarmal biber veniam gördüm qui sed bilgiyasayarı quia. Eum vel filmini iusto.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Göze labore camisi fugit sit tempora voluptate tv mutlu dignissimos sit çobanın sequi nemo eve nemo enim camisi ut reprehenderit balıkhaneye sed.",
                            Title = "Qui."
                        },
                        new
                        {
                            Id = 8,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 7, 23, 1, 3, 4, 5, DateTimeKind.Local).AddTicks(440),
                            Description = "Biber uzattı çorba un suscipit çobanın. Architecto quae accusantium domates sit. Quae qui consequatur kutusu yaptı ışık adresini sequi uzattı oldular. Çarpan cesurca voluptatem cesurca reprehenderit sed dışarı. Consequatur quia bilgiyasayarı sinema sandalye sıfat qui lakin voluptatem alias. Domates aspernatur sarmal et anlamsız patlıcan alias exercitationem göze.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Labore aspernatur beatae sevindi hesap sit qui sıla sequi modi salladı layıkıyla sed magni labore et accusantium ona neque sandalye de.",
                            Title = "Çorba."
                        },
                        new
                        {
                            Id = 9,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2023, 1, 7, 17, 26, 28, 50, DateTimeKind.Local).AddTicks(5971),
                            Description = "İpsum consequuntur voluptatem değirmeni sarmal suscipit. Sokaklarda lambadaki değerli commodi commodi illo amet beğendim. Balıkhaneye hesap consequatur dolorem batarya koyun için gördüm ea.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Odit voluptatem illo sequi çobanın corporis çorba eaque voluptatem in quia ipsa reprehenderit nihil dolayı.",
                            Title = "Ad suscipit duyulmamış ki sıfat kutusu biber."
                        },
                        new
                        {
                            Id = 10,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 8, 16, 2, 12, 51, 415, DateTimeKind.Local).AddTicks(5096),
                            Description = "Vitae eos ut in düşünüyor karşıdakine. Consequuntur dolayı sevindi exercitationem rem ullam için filmini sandalye architecto. Et explicabo inventore enim çünkü explicabo orta numquam. Dolore lakin qui domates ipsam laudantium. Gül suscipit salladı dignissimos gül sit değirmeni.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Amet adresini autem mıknatıslı ki için sevindi enim masaya quis balıkhaneye vitae çarpan minima.",
                            Title = "Dağılımı sinema gördüm labore praesentium dignissimos ve ut."
                        },
                        new
                        {
                            Id = 11,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2023, 2, 13, 1, 14, 40, 484, DateTimeKind.Local).AddTicks(6497),
                            Description = "Quae mıknatıslı cezbelendi odio. De domates sit. Hesap kutusu dağılımı esse aliquid. Sunt numquam çobanın quis sayfası vel duyulmamış kutusu dolore sandalye. Aut bahar şafak explicabo ratione sayfası amet çakıl doloremque olduğu. Yaptı reprehenderit esse ipsa.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Laboriosam gülüyorum kutusu nesciunt ex göze umut ut eos de ama türemiş orta magni ona ratione dignissimos ışık ut adipisci voluptatum neque gördüm bilgiyasayarı ex un alias cezbelendi fugit nostrum.",
                            Title = "Sıradanlıktan rem hesap explicabo architecto göze dışarı."
                        },
                        new
                        {
                            Id = 12,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 10, 19, 1, 36, 10, 588, DateTimeKind.Local).AddTicks(7444),
                            Description = "Telefonu değirmeni otobüs makinesi balıkhaneye quae gidecekmiş değirmeni magni amet. Kalemi fugit reprehenderit voluptatum. Türemiş mi dağılımı ötekinden. Ötekinden gülüyorum sıradanlıktan sit sed.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Layıkıyla qui blanditiis adipisci teldeki değirmeni consequatur corporis autem modi velit gidecekmiş eum quia açılmadan ullam ut ut patlıcan qui çıktılar quis in sit balıkhaneye veniam aut nostrum dolorem nostrum.",
                            Title = "Bundan inventore veritatis ut et adresini için anlamsız."
                        },
                        new
                        {
                            Id = 13,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2023, 4, 3, 22, 57, 25, 604, DateTimeKind.Local).AddTicks(6901),
                            Description = "Aliquam corporis magni bilgiyasayarı aspernatur düşünüyor. Kutusu aperiam tv yapacakmış beğendim adipisci uzattı ipsum ducimus sit. Hesap dolore ut incidunt dağılımı biber doloremque doğru tv eum.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Qui kalemi ipsum voluptatem dağılımı voluptatem ut ona çıktılar dolorem değirmeni quae quam adresini ipsam nemo değerli adanaya consequuntur bilgisayarı sequi gördüm.",
                            Title = "Işık çıktılar sit."
                        },
                        new
                        {
                            Id = 14,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2023, 3, 19, 22, 46, 20, 184, DateTimeKind.Local).AddTicks(3230),
                            Description = "Adipisci çobanın dolayı filmini adipisci sit orta mıknatıslı sevindi magnam. Nostrum göze laudantium quia. İncidunt patlıcan vel. Dolore sandalye sequi gördüm mıknatıslı. Bilgisayarı nostrum vitae voluptatum çarpan consequuntur deleniti quia. Çakıl voluptatem eius accusantium sevindi quis lambadaki.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Layıkıyla aut laboriosam domates sunt kutusu iure un hesap batarya çünkü numquam camisi ona consequatur teldeki voluptatem çıktılar deleniti sed ratione.",
                            Title = "Çıktılar de ea modi sevindi masaya."
                        },
                        new
                        {
                            Id = 15,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 8, 2, 20, 5, 8, 90, DateTimeKind.Local).AddTicks(9239),
                            Description = "Gül voluptas nesciunt quasi düşünüyor orta ea nemo. Sıfat sunt exercitationem koyun blanditiis. Dergi ducimus ex consequatur quia teldeki. Adanaya voluptatem ut eos değirmeni gidecekmiş dergi laudantium. Olduğu esse nostrum nemo çarpan yapacakmış duyulmamış ötekinden otobüs veniam. Laboriosam ışık modi quam balıkhaneye laudantium deleniti.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Değerli et nihil veritatis koyun karşıdakine anlamsız explicabo ab ekşili.",
                            Title = "Şafak veniam de accusantium ve adanaya praesentium eum kulu çıktılar."
                        },
                        new
                        {
                            Id = 16,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2023, 1, 25, 6, 28, 39, 897, DateTimeKind.Local).AddTicks(2329),
                            Description = "Quis nesciunt gördüm. Koşuyorlar suscipit consequatur consequatur fugit. Aliquid eos sinema quia ab dignissimos. Sed veniam inventore commodi voluptatem beğendim ışık aut bahar. Quaerat eos aliquid. Qui non dolores consequuntur quasi masanın.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Göze mi aspernatur bundan anlamsız voluptatem voluptatem quam ut odio odit ipsum dolayı minima aliquid.",
                            Title = "Filmini tv aut."
                        },
                        new
                        {
                            Id = 17,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 12, 23, 0, 20, 28, 298, DateTimeKind.Local).AddTicks(662),
                            Description = "Biber enim ratione. Ut sarmal voluptatem dolores değerli sit. Çünkü sevindi ab. Eaque duyulmamış voluptas ona. Aperiam molestiae domates et ut sit.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Ullam totam sarmal sequi makinesi bahar laboriosam ipsa corporis anlamsız quasi velit aut çünkü consectetur ducimus ullam gül değirmeni masanın aut alias incidunt.",
                            Title = "Reprehenderit laudantium şafak sıla."
                        },
                        new
                        {
                            Id = 18,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 10, 30, 3, 40, 25, 398, DateTimeKind.Local).AddTicks(1812),
                            Description = "Sıradanlıktan sandalye nisi incidunt tv bilgisayarı odit. Dolorem sıradanlıktan olduğu enim değirmeni çorba velit veritatis kutusu modi. Odit velit aperiam gül dolayı sıradanlıktan autem.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Velit oldular qui cezbelendi velit koşuyorlar neque masaya değirmeni quam sit ut deleniti quia eius ipsum perferendis ea.",
                            Title = "Yapacakmış vitae nihil ki düşünüyor nihil ipsum et."
                        },
                        new
                        {
                            Id = 19,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 12, 21, 7, 8, 45, 864, DateTimeKind.Local).AddTicks(8771),
                            Description = "İusto et sit commodi sit fugit adanaya. Velit bundan ut filmini. Camisi sıfat corporis et kulu quis. Architecto amet velit sıla. Dolorem uzattı magnam. Voluptatem voluptatem blanditiis rem anlamsız.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Koşuyorlar teldeki nisi explicabo velit odio enim çıktılar suscipit voluptatem mi ve.",
                            Title = "İçin dergi cesurca."
                        },
                        new
                        {
                            Id = 20,
                            AppUserId = 1,
                            CreatedAt = new DateTime(2022, 8, 22, 23, 17, 6, 981, DateTimeKind.Local).AddTicks(8606),
                            Description = "Nisi bilgisayarı laudantium laboriosam gül. Ratione neque consequatur karşıdakine magni ışık molestiae suscipit. Göze iusto sit exercitationem consequatur cezbelendi. Nisi eaque ratione incidunt. Değerli neque quaerat yapacakmış dolayı sed.",
                            ImagePath = "default.jpeg",
                            ShortDescription = "Dolor quis consequuntur aperiam batarya et voluptatem eve iusto dolayı ea türemiş sit göze sayfası eaque oldular orta quasi gülüyorum adresini oldular sandalye gazete.",
                            Title = "Quam suscipit orta sit camisi bundan."
                        });
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.BlogCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("CategoryId", "BlogId");

                    b.ToTable("BlogCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            BlogId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            BlogId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            BlogId = 7,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 8,
                            BlogId = 8,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 9,
                            BlogId = 9,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 10,
                            BlogId = 10,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 11,
                            BlogId = 11,
                            CategoryId = 6
                        },
                        new
                        {
                            Id = 12,
                            BlogId = 12,
                            CategoryId = 6
                        },
                        new
                        {
                            Id = 13,
                            BlogId = 13,
                            CategoryId = 7
                        },
                        new
                        {
                            Id = 14,
                            BlogId = 14,
                            CategoryId = 7
                        },
                        new
                        {
                            Id = 15,
                            BlogId = 15,
                            CategoryId = 8
                        },
                        new
                        {
                            Id = 16,
                            BlogId = 16,
                            CategoryId = 8
                        },
                        new
                        {
                            Id = 17,
                            BlogId = 17,
                            CategoryId = 9
                        },
                        new
                        {
                            Id = 18,
                            BlogId = 18,
                            CategoryId = 9
                        },
                        new
                        {
                            Id = 19,
                            BlogId = 19,
                            CategoryId = 10
                        },
                        new
                        {
                            Id = 20,
                            BlogId = 20,
                            CategoryId = 10
                        });
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books & Home"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Industrial & Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sports & Beauty"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Toys & Shoes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Outdoors & Shoes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Electronics & Home"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tools & Health"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jewelery"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kids & Garden"
                        });
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorEmail = "Avluc0@yahoo.com",
                            AuthorName = "İkeme Çetiner",
                            BlogId = 9,
                            CreatedAt = new DateTime(2023, 3, 8, 4, 11, 35, 255, DateTimeKind.Local).AddTicks(7861),
                            Description = "Molestiae mıknatıslı sit et açılmadan sayfası perferendis rem. Layıkıyla ea sinema gitti. Bilgiyasayarı sunt consectetur."
                        },
                        new
                        {
                            Id = 2,
                            AuthorEmail = "Aydarkagan13@hotmail.com",
                            AuthorName = "Bulak Tuğlu",
                            BlogId = 9,
                            CreatedAt = new DateTime(2023, 1, 9, 18, 7, 11, 970, DateTimeKind.Local).AddTicks(919),
                            Description = "Göze eaque umut ab suscipit sıla enim bahar layıkıyla. Veniam quaerat voluptatum cezbelendi aut eos. Dolor dolor alias."
                        },
                        new
                        {
                            Id = 3,
                            AuthorEmail = "Bozboru.Tutuncu@yahoo.com",
                            AuthorName = "Asığ Türkdoğan",
                            BlogId = 3,
                            CreatedAt = new DateTime(2023, 4, 1, 21, 25, 26, 644, DateTimeKind.Local).AddTicks(2992),
                            Description = "Kapının architecto sit dicta commodi aperiam odit dolayı. Adipisci blanditiis autem karşıdakine nemo explicabo qui masaya teldeki sed. Ex koştum eum iure değerli."
                        },
                        new
                        {
                            Id = 4,
                            AuthorEmail = "Bayna91@hotmail.com",
                            AuthorName = "Alp Çörekçi",
                            BlogId = 12,
                            CreatedAt = new DateTime(2022, 7, 13, 14, 23, 3, 531, DateTimeKind.Local).AddTicks(3559),
                            Description = "Düşünüyor kulu voluptatem. Yazın veniam patlıcan. Velit rem amet aliquam modi commodi çobanın. Çıktılar eaque odit dolore consequatur. Sıradanlıktan otobüs eius yapacakmış consectetur. Quia dışarı gitti sokaklarda gül ut un umut fugit."
                        },
                        new
                        {
                            Id = 5,
                            AuthorEmail = "Balakatay50@hotmail.com",
                            AuthorName = "Börübars Egeli",
                            BlogId = 17,
                            CreatedAt = new DateTime(2022, 12, 18, 11, 42, 51, 794, DateTimeKind.Local).AddTicks(9353),
                            Description = "Çakıl quaerat sit gülüyorum nisi. Fugit modi quia qui eum dolorem gazete quis. Koyun ekşili duyulmamış."
                        },
                        new
                        {
                            Id = 6,
                            AuthorEmail = "Engin_Yetkiner@hotmail.com",
                            AuthorName = "Badabul Adan",
                            BlogId = 18,
                            CreatedAt = new DateTime(2023, 2, 27, 5, 41, 18, 536, DateTimeKind.Local).AddTicks(4361),
                            Description = "Veniam dicta balıkhaneye ab. Ex esse voluptatem qui çünkü orta numquam suscipit ve ve. Eve uzattı eum sayfası ullam cesurca çünkü veniam ea sayfası. Açılmadan dağılımı voluptatum reprehenderit ipsum."
                        },
                        new
                        {
                            Id = 7,
                            AuthorEmail = "Bagaisbara.Ayverdi79@gmail.com",
                            AuthorName = "Abşar Akaydın",
                            BlogId = 9,
                            CreatedAt = new DateTime(2022, 10, 18, 22, 11, 31, 844, DateTimeKind.Local).AddTicks(6809),
                            Description = "Duyulmamış molestiae domates gidecekmiş laboriosam. Nemo laboriosam salladı cezbelendi. Adanaya çünkü batarya in un quam."
                        },
                        new
                        {
                            Id = 8,
                            AuthorEmail = "Borlukcu_Kuzucu@hotmail.com",
                            AuthorName = "Arnaç Akgül",
                            BlogId = 19,
                            CreatedAt = new DateTime(2022, 12, 1, 14, 35, 49, 827, DateTimeKind.Local).AddTicks(217),
                            Description = "Çıktılar et sevindi sokaklarda eaque. Neque voluptatum beğendim quia voluptatem voluptatem. Bundan iure sinema. İn bahar qui commodi gitti çobanın sit beğendim ex."
                        },
                        new
                        {
                            Id = 9,
                            AuthorEmail = "Calapkulu.Oymen@hotmail.com",
                            AuthorName = "Erentüz Dağlaroğlu",
                            BlogId = 20,
                            CreatedAt = new DateTime(2023, 4, 11, 22, 3, 2, 97, DateTimeKind.Local).AddTicks(8902),
                            Description = "Sed gitti layıkıyla magnam. Velit bilgisayarı quia ratione alias accusantium laudantium in oldular quaerat. Odio ve değirmeni mıknatıslı bilgiyasayarı ipsam. Totam ad eaque beatae tempora. Cesurca inventore şafak batarya deleniti düşünüyor sit consequuntur vel kutusu. İure layıkıyla voluptatem incidunt sevindi koştum eos batarya dicta amet."
                        },
                        new
                        {
                            Id = 10,
                            AuthorEmail = "Aydemir.Egeli@hotmail.com",
                            AuthorName = "Bükebuyruç Akşit",
                            BlogId = 1,
                            CreatedAt = new DateTime(2022, 11, 20, 17, 55, 29, 549, DateTimeKind.Local).AddTicks(9899),
                            Description = "Esse ad consequatur gitti aperiam sit dolore sandalye. Ex ekşili bilgiyasayarı adanaya fugit. Oldular ut anlamsız."
                        },
                        new
                        {
                            Id = 11,
                            AuthorEmail = "Beckem_Cevik95@gmail.com",
                            AuthorName = "Alpturan Sözeri",
                            BlogId = 11,
                            CreatedAt = new DateTime(2022, 11, 23, 14, 26, 17, 967, DateTimeKind.Local).AddTicks(1087),
                            Description = "Quasi corporis et dolores layıkıyla un. Eum non inventore alias düşünüyor. Bilgisayarı adanaya umut incidunt değerli sed praesentium et biber deleniti. Non koşuyorlar okuma consectetur inventore ut çıktılar. Quia ea koştum çünkü ışık perferendis. Qui aut ona koyun sed kapının odio sıla aspernatur."
                        },
                        new
                        {
                            Id = 12,
                            AuthorEmail = "Bekecarslantegin75@hotmail.com",
                            AuthorName = "Çobulmak Çevik",
                            BlogId = 15,
                            CreatedAt = new DateTime(2022, 9, 26, 21, 9, 59, 566, DateTimeKind.Local).AddTicks(3889),
                            Description = "Ötekinden sayfası laboriosam gazete karşıdakine quis quis. Çorba ad vitae et neque nihil çakıl accusantium quis. Ekşili değirmeni voluptate için duyulmamış gitti neque quia. Ad consequatur sokaklarda sit olduğu çıktılar sequi sayfası mutlu. Mıknatıslı ullam praesentium. Karşıdakine consectetur cezbelendi bilgisayarı."
                        },
                        new
                        {
                            Id = 13,
                            AuthorEmail = "Baydar.Bolatli@hotmail.com",
                            AuthorName = "Işıl Erbay",
                            BlogId = 20,
                            CreatedAt = new DateTime(2022, 7, 10, 13, 34, 59, 750, DateTimeKind.Local).AddTicks(4919),
                            Description = "Cesurca ratione deleniti bundan göze değerli odit ötekinden blanditiis. Praesentium uzattı mi quis. Vel nemo deleniti doğru in yaptı sıradanlıktan lakin çıktılar. Ea incidunt nihil bahar eum laboriosam. Commodi quis explicabo teldeki olduğu et çakıl beatae. Kapının patlıcan batarya değerli ab bilgiyasayarı accusantium teldeki."
                        },
                        new
                        {
                            Id = 14,
                            AuthorEmail = "Keyken29@gmail.com",
                            AuthorName = "Atış Akan",
                            BlogId = 1,
                            CreatedAt = new DateTime(2023, 1, 18, 0, 48, 5, 388, DateTimeKind.Local).AddTicks(537),
                            Description = "Eos modi sıradanlıktan veritatis. Sed gazete adanaya corporis sayfası çakıl otobüs çünkü gördüm. Ullam aliquam quae blanditiis totam numquam. Cesurca uzattı sıradanlıktan gördüm adanaya commodi magni perferendis aspernatur nihil."
                        },
                        new
                        {
                            Id = 15,
                            AuthorEmail = "Aybalta.Arslanoglu@yahoo.com",
                            AuthorName = "Baltur Erçetin",
                            BlogId = 3,
                            CreatedAt = new DateTime(2023, 4, 12, 20, 43, 43, 96, DateTimeKind.Local).AddTicks(5320),
                            Description = "Esse eum yaptı sequi sit totam amet layıkıyla eum. Işık sıla otobüs umut ipsum. Aspernatur modi çakıl. İçin hesap commodi eaque tv. Et non sinema veniam dolore incidunt enim corporis kalemi ea."
                        },
                        new
                        {
                            Id = 16,
                            AuthorEmail = "Bickici_Denkel98@gmail.com",
                            AuthorName = "Güler Dizdar ",
                            BlogId = 20,
                            CreatedAt = new DateTime(2022, 6, 28, 7, 20, 27, 11, DateTimeKind.Local).AddTicks(6452),
                            Description = "Çünkü reprehenderit voluptatem filmini odit veniam odio ve. Çorba labore ipsa sunt aut mutlu umut laudantium kulu. Sayfası aperiam camisi cezbelendi. Et sinema nemo commodi mi suscipit ut reprehenderit. Beğendim minima laboriosam yapacakmış. Laboriosam nisi quia dolor laboriosam."
                        },
                        new
                        {
                            Id = 17,
                            AuthorEmail = "Barmakli.Karaer@yahoo.com",
                            AuthorName = "Adalan Dağdaş",
                            BlogId = 18,
                            CreatedAt = new DateTime(2023, 4, 16, 9, 34, 45, 752, DateTimeKind.Local).AddTicks(6471),
                            Description = "Çorba nemo dolores adipisci quae mıknatıslı veritatis enim. Eaque lakin balıkhaneye nesciunt ratione suscipit nemo kulu velit deleniti. Voluptate vitae velit labore fugit un."
                        },
                        new
                        {
                            Id = 18,
                            AuthorEmail = "Asartegin_Yetkiner@hotmail.com",
                            AuthorName = "Bağa Yorulmaz",
                            BlogId = 2,
                            CreatedAt = new DateTime(2023, 4, 26, 1, 35, 53, 76, DateTimeKind.Local).AddTicks(7435),
                            Description = "Consectetur laboriosam vel eos ea karşıdakine quis cezbelendi voluptatum. Işık batarya sit filmini açılmadan praesentium magnam ratione. Nihil ipsam çünkü hesap velit sed koşuyorlar. Rem ekşili incidunt gidecekmiş teldeki. Consequatur aut neque velit uzattı tempora."
                        },
                        new
                        {
                            Id = 19,
                            AuthorEmail = "Bolmus_Kuday40@gmail.com",
                            AuthorName = "Algu Balaban",
                            BlogId = 7,
                            CreatedAt = new DateTime(2022, 10, 17, 22, 45, 4, 815, DateTimeKind.Local).AddTicks(2722),
                            Description = "Eaque blanditiis yapacakmış lambadaki gidecekmiş cezbelendi ut. Accusantium dolayı quia odio sed. Doloremque aut corporis bundan türemiş sıradanlıktan ab ipsam blanditiis anlamsız. Voluptate filmini neque ab dolore consectetur sit camisi."
                        },
                        new
                        {
                            Id = 20,
                            AuthorEmail = "Bumen_Pektemek@yahoo.com",
                            AuthorName = "Baybora Aclan",
                            BlogId = 15,
                            CreatedAt = new DateTime(2022, 9, 8, 11, 42, 59, 524, DateTimeKind.Local).AddTicks(5419),
                            Description = "İnventore de perferendis sıfat sayfası. Et sinema ki. Bundan telefonu quia masaya dışarı kulu laboriosam. Aut ex batarya çünkü non consequatur eaque. Alias ex voluptas."
                        },
                        new
                        {
                            Id = 21,
                            AuthorEmail = "Bayuncur_Tasli@gmail.com",
                            AuthorName = "Atımer Çevik",
                            BlogId = 2,
                            CreatedAt = new DateTime(2022, 6, 15, 2, 13, 8, 510, DateTimeKind.Local).AddTicks(2284),
                            Description = "Perferendis dolores totam amet. Ve karşıdakine exercitationem. Suscipit deleniti nemo aperiam düşünüyor odio patlıcan voluptatem voluptatem. Consequatur nesciunt enim velit ea accusantium enim. Koyun tv dolayı yazın perferendis magni in. Uzattı çorba tempora sed voluptatem lambadaki bilgiyasayarı."
                        },
                        new
                        {
                            Id = 22,
                            AuthorEmail = "Inc31@hotmail.com",
                            AuthorName = "Bayram Pekkan",
                            BlogId = 1,
                            CreatedAt = new DateTime(2022, 9, 20, 21, 15, 37, 683, DateTimeKind.Local).AddTicks(3847),
                            Description = "Un incidunt iure bundan in cezbelendi uzattı corporis ratione dolorem. Düşünüyor dolores dolorem explicabo. Eaque dolores commodi quia quia dicta."
                        },
                        new
                        {
                            Id = 23,
                            AuthorEmail = "Irinckol.Alpugan@hotmail.com",
                            AuthorName = "Çimen Yeşilkaya",
                            BlogId = 7,
                            CreatedAt = new DateTime(2022, 11, 8, 1, 2, 37, 158, DateTimeKind.Local).AddTicks(7120),
                            Description = "Quam türemiş sinema eius düşünüyor batarya numquam velit veniam quam. Nisi sed beğendim laboriosam batarya aliquid karşıdakine orta. Ekşili okuma laboriosam açılmadan gitti otobüs ve labore ex."
                        },
                        new
                        {
                            Id = 24,
                            AuthorEmail = "Atalmis24@yahoo.com",
                            AuthorName = "Gönül Akay",
                            BlogId = 11,
                            CreatedAt = new DateTime(2022, 8, 20, 12, 37, 54, 222, DateTimeKind.Local).AddTicks(9855),
                            Description = "Mi dağılımı quis ötekinden ea ratione. Explicabo sunt sunt sıradanlıktan lakin ullam alias quia ipsum dignissimos. Gitti fugit commodi de de et voluptatem. Sed odio lambadaki masaya voluptatum. Domates ducimus karşıdakine ekşili dignissimos modi cesurca ut. Tempora cesurca perferendis voluptate doğru blanditiis ipsa ab velit alias."
                        },
                        new
                        {
                            Id = 25,
                            AuthorEmail = "Bayik_Baykam@hotmail.com",
                            AuthorName = "Aydınalp Çatalbaş",
                            BlogId = 7,
                            CreatedAt = new DateTime(2022, 8, 29, 20, 33, 33, 715, DateTimeKind.Local).AddTicks(4841),
                            Description = "Vel accusantium inventore mutlu quae için qui voluptatem eaque çorba. Voluptatem ona ducimus quis sinema. Dignissimos aliquid modi doğru eos ut sit."
                        },
                        new
                        {
                            Id = 26,
                            AuthorEmail = "Bayincur_Kirac@gmail.com",
                            AuthorName = "Bağaturipi Gürmen",
                            BlogId = 10,
                            CreatedAt = new DateTime(2022, 7, 29, 19, 14, 36, 352, DateTimeKind.Local).AddTicks(2763),
                            Description = "Ki sokaklarda qui orta gül oldular velit. Mi numquam nisi. Dolorem gazete değerli sarmal de corporis quia consequuntur. Esse olduğu sed dolor koşuyorlar ratione quia quia bilgiyasayarı perferendis. Sunt eaque non et uzattı."
                        },
                        new
                        {
                            Id = 27,
                            AuthorEmail = "Alperen_Bicer28@yahoo.com",
                            AuthorName = "Alabörü Ertürk",
                            BlogId = 17,
                            CreatedAt = new DateTime(2022, 11, 29, 14, 34, 33, 5, DateTimeKind.Local).AddTicks(7899),
                            Description = "Totam kulu praesentium praesentium teldeki veritatis sunt. Masanın yaptı autem sinema çobanın aut un layıkıyla reprehenderit. Bundan minima okuma ea qui nihil sed exercitationem."
                        },
                        new
                        {
                            Id = 28,
                            AuthorEmail = "Bilgekagan_Kececi40@gmail.com",
                            AuthorName = "Bıtrı Hakyemez",
                            BlogId = 20,
                            CreatedAt = new DateTime(2022, 8, 17, 18, 46, 24, 126, DateTimeKind.Local).AddTicks(2882),
                            Description = "Sed doloremque voluptatem eve dolorem adanaya tv deleniti yapacakmış. Voluptatem camisi aut teldeki adresini. Laudantium sandalye modi lambadaki teldeki blanditiis olduğu. İpsa sandalye modi gülüyorum alias ex un fugit minima. Aut dolores lakin domates ki ratione enim molestiae."
                        },
                        new
                        {
                            Id = 29,
                            AuthorEmail = "Berke19@yahoo.com",
                            AuthorName = "İlbilge Adıvar",
                            BlogId = 7,
                            CreatedAt = new DateTime(2023, 5, 16, 12, 23, 46, 656, DateTimeKind.Local).AddTicks(4190),
                            Description = "Sinema bilgiyasayarı cezbelendi sıradanlıktan koşuyorlar tempora anlamsız batarya bundan. Patlıcan vitae çünkü ab sit bilgiyasayarı ipsum koyun. Çünkü eius masanın architecto et yazın camisi adanaya. Sıfat kulu dağılımı sarmal. Magni voluptatum ratione bahar reprehenderit gül."
                        },
                        new
                        {
                            Id = 30,
                            AuthorEmail = "Begarslan.Ertepinar@gmail.com",
                            AuthorName = "Baykuzu Alpuğan",
                            BlogId = 2,
                            CreatedAt = new DateTime(2023, 5, 10, 19, 9, 32, 312, DateTimeKind.Local).AddTicks(7676),
                            Description = "Lambadaki totam esse eaque aperiam qui adresini ullam in eum. Mıknatıslı quaerat de odio modi minima. Tv ea otobüs eaque ut. Makinesi eaque sit aperiam ötekinden sıradanlıktan esse. Gazete iusto exercitationem de aut quia sequi sinema voluptatem. Beğendim ışık oldular voluptatem lakin."
                        },
                        new
                        {
                            Id = 31,
                            AuthorEmail = "Cingir17@yahoo.com",
                            AuthorName = "Başak Babaoğlu",
                            BlogId = 4,
                            CreatedAt = new DateTime(2023, 4, 9, 4, 38, 29, 914, DateTimeKind.Local).AddTicks(9633),
                            Description = "Et qui qui vitae filmini qui ona eum domates. Layıkıyla beğendim aspernatur corporis sandalye esse nemo ab açılmadan. Quis explicabo ad exercitationem consequatur minima."
                        },
                        new
                        {
                            Id = 32,
                            AuthorEmail = "Artiinal.Dusenkalkar@hotmail.com",
                            AuthorName = "Çağrı Karaduman",
                            BlogId = 18,
                            CreatedAt = new DateTime(2023, 1, 14, 3, 31, 22, 386, DateTimeKind.Local).AddTicks(104),
                            Description = "Autem gitti kulu qui. Yazın için öyle. Quam magni fugit ea adresini voluptate voluptas mıknatıslı ea dağılımı. Sequi aut şafak yazın lakin balıkhaneye şafak minima. Ama ışık ex exercitationem nesciunt dolore ea domates aut qui."
                        },
                        new
                        {
                            Id = 33,
                            AuthorEmail = "Bunsuz88@gmail.com",
                            AuthorName = "Aşantuğrul Elmastaşoğlu",
                            BlogId = 14,
                            CreatedAt = new DateTime(2023, 1, 12, 18, 16, 57, 188, DateTimeKind.Local).AddTicks(7578),
                            Description = "Dolayı layıkıyla modi dignissimos vitae beatae explicabo. Voluptatum quia aspernatur magni labore sandalye qui. İpsam çobanın quis. Quia makinesi et dignissimos aperiam consequatur illo alias. Voluptatum bilgisayarı dolores praesentium layıkıyla odio."
                        },
                        new
                        {
                            Id = 34,
                            AuthorEmail = "Burulgu26@hotmail.com",
                            AuthorName = "Bulmuş Yalçın",
                            BlogId = 4,
                            CreatedAt = new DateTime(2023, 5, 8, 0, 25, 14, 817, DateTimeKind.Local).AddTicks(6245),
                            Description = "Gazete ratione eve sayfası qui nemo çakıl koştum batarya değirmeni. Işık eve ipsum. Biber un gördüm accusantium layıkıyla beatae gidecekmiş. Balıkhaneye dağılımı consequatur praesentium dicta mi ötekinden deleniti duyulmamış. Göze bilgisayarı düşünüyor ex domates filmini filmini ut. Biber inventore aliquid yapacakmış adipisci."
                        },
                        new
                        {
                            Id = 35,
                            AuthorEmail = "Barcadurdu57@yahoo.com",
                            AuthorName = "Arıkağan Köylüoğlu",
                            BlogId = 19,
                            CreatedAt = new DateTime(2022, 9, 18, 4, 34, 41, 987, DateTimeKind.Local).AddTicks(2065),
                            Description = "Dicta bilgiyasayarı incidunt consequuntur sit magni totam çarpan adipisci ratione. Nihil adipisci exercitationem değerli patlıcan kapının hesap kulu. Mi iusto dergi sit alias minima quis."
                        },
                        new
                        {
                            Id = 36,
                            AuthorEmail = "Bumen3@yahoo.com",
                            AuthorName = "Baybora Barbarosoğlu",
                            BlogId = 5,
                            CreatedAt = new DateTime(2022, 8, 25, 18, 39, 51, 843, DateTimeKind.Local).AddTicks(7124),
                            Description = "Dağılımı şafak kulu çobanın. Non iusto rem eos çarpan. Cesurca voluptatum ışık bundan ut dergi alias velit. Ducimus ipsum enim. Aut aut salladı laboriosam ipsa autem ea sed biber gördüm. Non fugit labore aspernatur eos voluptate neque incidunt değirmeni dolorem."
                        },
                        new
                        {
                            Id = 37,
                            AuthorEmail = "Atli10@yahoo.com",
                            AuthorName = "Çağrıtegin Arıcan",
                            BlogId = 20,
                            CreatedAt = new DateTime(2022, 7, 4, 19, 37, 4, 997, DateTimeKind.Local).AddTicks(8869),
                            Description = "Değirmeni adipisci sokaklarda açılmadan ullam. Ab teldeki sequi. Ad yazın eve aut sit aperiam sit oldular yapacakmış. Tempora masanın masanın adanaya sit anlamsız mıknatıslı değirmeni commodi. Ab sayfası ut vitae."
                        },
                        new
                        {
                            Id = 38,
                            AuthorEmail = "Artut32@yahoo.com",
                            AuthorName = "Bakağul Saygıner",
                            BlogId = 15,
                            CreatedAt = new DateTime(2022, 10, 5, 8, 3, 12, 851, DateTimeKind.Local).AddTicks(5914),
                            Description = "Aliquam orta consequatur. Nesciunt deleniti kulu. Mutlu beatae gazete tempora. Quis mıknatıslı aut otobüs eve kalemi mıknatıslı. Oldular gidecekmiş deleniti."
                        },
                        new
                        {
                            Id = 39,
                            AuthorEmail = "Bidin.Agaoglu@yahoo.com",
                            AuthorName = "Baybiçen Hakyemez",
                            BlogId = 2,
                            CreatedAt = new DateTime(2023, 1, 24, 13, 7, 54, 805, DateTimeKind.Local).AddTicks(900),
                            Description = "Bahar beatae sed patlıcan eos qui sed sıfat bilgisayarı eve. Magnam gülüyorum ışık voluptatem olduğu consequatur ab dolorem olduğu. Sequi ut blanditiis quia sandalye dağılımı türemiş odit."
                        },
                        new
                        {
                            Id = 40,
                            AuthorEmail = "Cabus_Pektemek73@hotmail.com",
                            AuthorName = "Bükebuyruç Tokatlıoğlu",
                            BlogId = 19,
                            CreatedAt = new DateTime(2022, 9, 7, 1, 10, 27, 368, DateTimeKind.Local).AddTicks(6287),
                            Description = "Gidecekmiş ve karşıdakine sayfası dolor. Odit nisi çarpan ona eaque mi et velit masaya çakıl. Türemiş quia masanın consequatur umut incidunt beğendim ki praesentium. Dolorem explicabo ut."
                        },
                        new
                        {
                            Id = 41,
                            AuthorEmail = "Bugrakarakagan84@gmail.com",
                            AuthorName = "Arkış Uca",
                            BlogId = 12,
                            CreatedAt = new DateTime(2022, 8, 2, 8, 55, 57, 530, DateTimeKind.Local).AddTicks(1010),
                            Description = "Velit consectetur gazete için fugit vel voluptatem sayfası sequi. Non açılmadan sed ekşili gördüm odit praesentium gülüyorum gazete açılmadan. Dışarı sarmal incidunt ea. Sit non değirmeni explicabo vel ve. Yapacakmış accusantium dolores consequuntur quia de sıla veniam. Blanditiis ut uzattı velit cesurca quam exercitationem."
                        },
                        new
                        {
                            Id = 42,
                            AuthorEmail = "Basci.Adivar53@yahoo.com",
                            AuthorName = "Armağan Özdoğan",
                            BlogId = 9,
                            CreatedAt = new DateTime(2022, 12, 23, 23, 15, 32, 262, DateTimeKind.Local).AddTicks(9043),
                            Description = "Değirmeni corporis batarya voluptatem aut umut. Dolor mıknatıslı esse un ışık dergi velit consequuntur türemiş alias. Cezbelendi otobüs cesurca velit quaerat sed. Sıfat voluptatem ea ab dağılımı qui kulu laboriosam. Ut kapının sıfat çakıl sequi et. Tv balıkhaneye göze in voluptatem."
                        },
                        new
                        {
                            Id = 43,
                            AuthorEmail = "Burkay.Abaci69@hotmail.com",
                            AuthorName = "Balamır Taşlı",
                            BlogId = 1,
                            CreatedAt = new DateTime(2023, 4, 12, 16, 7, 10, 359, DateTimeKind.Local).AddTicks(389),
                            Description = "Sit sequi teldeki voluptatum. Nemo dolayı yaptı. Dağılımı in ut. Dolor autem ipsum bundan sed beatae consequatur velit veritatis qui. Eius quia esse quae perferendis."
                        },
                        new
                        {
                            Id = 44,
                            AuthorEmail = "Beg.Cevik38@hotmail.com",
                            AuthorName = "Arademir Kaya ",
                            BlogId = 20,
                            CreatedAt = new DateTime(2023, 4, 1, 4, 22, 50, 652, DateTimeKind.Local).AddTicks(6013),
                            Description = "Layıkıyla ona vel batarya mıknatıslı gülüyorum suscipit. Un consequuntur ratione quaerat voluptatum aut ipsam enim. Patlıcan inventore amet dağılımı deleniti. Açılmadan voluptatum veritatis otobüs göze. Türemiş explicabo gidecekmiş."
                        },
                        new
                        {
                            Id = 45,
                            AuthorEmail = "Basademir44@yahoo.com",
                            AuthorName = "Alpdoğan Yeşilkaya",
                            BlogId = 7,
                            CreatedAt = new DateTime(2022, 10, 30, 4, 50, 35, 320, DateTimeKind.Local).AddTicks(3531),
                            Description = "İncidunt vitae quasi quam laudantium dağılımı umut sayfası cesurca. Masanın bahar reprehenderit duyulmamış et. Salladı quis patlıcan adanaya."
                        },
                        new
                        {
                            Id = 46,
                            AuthorEmail = "Arslanyabgu82@yahoo.com",
                            AuthorName = "Arkın Koçyiğit",
                            BlogId = 10,
                            CreatedAt = new DateTime(2022, 10, 18, 16, 42, 50, 99, DateTimeKind.Local).AddTicks(4644),
                            Description = "Et ex labore dolayı in in aliquid minima. Oldular exercitationem beğendim qui et. Ducimus masanın accusantium ona cezbelendi sit açılmadan mutlu. Aut sıla consequuntur quae perferendis aut quia enim domates."
                        },
                        new
                        {
                            Id = 47,
                            AuthorEmail = "Baybure46@hotmail.com",
                            AuthorName = "Gelincik Günday",
                            BlogId = 19,
                            CreatedAt = new DateTime(2023, 2, 16, 5, 34, 28, 250, DateTimeKind.Local).AddTicks(9991),
                            Description = "Gitti patlıcan değerli lambadaki laboriosam ama çünkü. Suscipit beğendim layıkıyla. Velit architecto consequatur okuma. Çünkü sequi magni laudantium ut ad sit kutusu. Masaya quia iure."
                        },
                        new
                        {
                            Id = 48,
                            AuthorEmail = "Erdenikatun_Yetkiner16@yahoo.com",
                            AuthorName = "Alpkara Demirbaş",
                            BlogId = 13,
                            CreatedAt = new DateTime(2023, 1, 21, 8, 12, 23, 980, DateTimeKind.Local).AddTicks(3955),
                            Description = "İnventore patlıcan modi olduğu düşünüyor koyun sevindi için. Quasi sit adresini exercitationem voluptatem. Öyle consequatur modi dignissimos. Dışarı sarmal consequatur odio olduğu quaerat. Beatae düşünüyor duyulmamış dolor rem adresini neque."
                        },
                        new
                        {
                            Id = 49,
                            AuthorEmail = "Baybicen43@gmail.com",
                            AuthorName = "Baturalp Pektemek",
                            BlogId = 5,
                            CreatedAt = new DateTime(2023, 1, 26, 3, 14, 38, 410, DateTimeKind.Local).AddTicks(1795),
                            Description = "Quae magni çıktılar quis karşıdakine koyun aliquam accusantium mıknatıslı aliquam. Et ullam quia tv exercitationem suscipit cezbelendi doloremque anlamsız masanın. Mi aut vel molestiae qui değerli qui esse dolor. Aspernatur dolayı laboriosam kulu quae numquam."
                        },
                        new
                        {
                            Id = 50,
                            AuthorEmail = "Atakagan54@yahoo.com",
                            AuthorName = "Çağrıbeğ Dağdaş",
                            BlogId = 8,
                            CreatedAt = new DateTime(2023, 3, 9, 1, 1, 53, 566, DateTimeKind.Local).AddTicks(1526),
                            Description = "Batarya autem quaerat amet laboriosam. Gül amet batarya batarya quia ut. Yaptı quia patlıcan ötekinden kapının consequatur sokaklarda çarpan. Ve batarya mutlu layıkıyla eum. İllo aliquam voluptatem velit."
                        });
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.AppUserRole", b =>
                {
                    b.HasOne("HttpClientTest.Entities.Models.AppRole", "AppRole")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HttpClientTest.Entities.Models.AppUser", "AppUser")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.Blog", b =>
                {
                    b.HasOne("HttpClientTest.Entities.Models.AppUser", "AppUser")
                        .WithMany("Blogs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.BlogCategory", b =>
                {
                    b.HasOne("HttpClientTest.Entities.Models.Blog", "Blog")
                        .WithMany("BlogCategories")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HttpClientTest.Entities.Models.Category", "Category")
                        .WithMany("BlogCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.Comment", b =>
                {
                    b.HasOne("HttpClientTest.Entities.Models.Blog", "Blog")
                        .WithMany("Comments")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HttpClientTest.Entities.Models.Comment", "ParentComment")
                        .WithMany("SubComment")
                        .HasForeignKey("ParentCommentId");

                    b.Navigation("Blog");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.AppRole", b =>
                {
                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.AppUser", b =>
                {
                    b.Navigation("AppUserRoles");

                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.Blog", b =>
                {
                    b.Navigation("BlogCategories");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.Category", b =>
                {
                    b.Navigation("BlogCategories");
                });

            modelBuilder.Entity("HttpClientTest.Entities.Models.Comment", b =>
                {
                    b.Navigation("SubComment");
                });
#pragma warning restore 612, 618
        }
    }
}
