global using FluentValidation.AspNetCore;
global using HttpClientTest.Common.ComplexTypes;
global using HttpClientTest.Dtos.CategoryDtos;
global using HttpClientTest.Service.Abstract;
global using HttpClientTest.Service.DependencyResolvers;
global using HttpClientTest.WebApi.CustomFilters;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using HttpClientTest.Dtos.BlogDtos;
